version: '3.8'

services:
  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334

  # James backend API
  james-api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - QDRANT_URL=http://qdrant:6333
      - JAMES_HOME=/app/.james
      - LANGCHAIN_PROJECT=james
      - LANGCHAIN_TRACING_V2=true
    volumes:
      - james_data:/app/.james
    depends_on:
      - qdrant
    restart: unless-stopped

  # James frontend UI
  james-ui:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - james-api
    restart: unless-stopped

volumes:
  qdrant_storage:
  james_data: